script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=3.0.0
  - PUPPET_VERSION=3.2.1
branches:
  only:
    - master
notifications:
  email: false
