language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
branches:
  only:
    - travis_testing
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
#  - PUPPET_VERSION="2.7.0"
#  - PUPPET_VERSION="3.0.0"
#  - PUPPET_VERSION="3.1.0"
  - PUPPET_GEM_VERSION=">= 3.0.0"
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
  include:
    - rvm: 1.8.7
    - env: PUPPET_GEM_VERSION="~> 2.7"
notifications:
  email: false
gemfile: .gemfile
